<?php
/**
 * @file
 * Code for the Image feature.
 */

include_once('mm_image.features.inc');

function mm_image_theme($existing, $type, $theme, $path) {
  return array(
    'node__image_gallery' => array(
      'render element' => 'elements',
      'path' => drupal_get_path('module', 'mm_image') . '/theme',
      'template' => 'node--image-gallery',
  ),
  );
}

function mm_image_preprocess_node(&$variables) {
  if($variables['type'] == 'image_gallery') {
    drupal_add_js(drupal_get_path('module', 'mm_image') . '/js/mm_image.js', 'file');
    $variables['images'] = '';
    foreach($variables['field_images'] as $key => $image) {
      $node = $image['node'];
      
      // filename relative to files directory
      // e.g. 'masthead.jpg'
      $filename = $node->field_image[$node->language][0]['filename'];

      // relative path to raw image in 'scheme' format
      // e.g. 'public://masthead.jpg'
      $uri = file_build_uri($filename);

      // raw URL with an image style
      // e.g. 'http://mysite.com/sites/default/files/styles/banner/public/masthead.jpg'
      // [passing a raw path here will return a very ungraceful fatal error, see http://api.drupal.org/api/drupal/modules--image--image.module/function/image_style_url/7#comment-12079]
      //$image_uri = image_style_url('large', $uri);

      $image_uri = file_create_url($uri);

      // html for a styled image
      // e.g. '<img typeof="foaf:Image" src="http://mysite.com/sites/default/files/styles/banner/public/masthead.jpg" alt="" />'
      $image_html = theme('image_style', array('style_name' => 'square_thumbnail', 'path' => $uri));

      $image_description = $node->field_mm_image_description[$node->language][0]['safe_value'];

      // l($text, $path, array $options = array())
      $image_link = l($image_html, $image_uri, array(
        'attributes' => array('class' => array('image-gallery'), 'title' => $image_description),
        'html' => TRUE
      ));

      $variables['images'] .= $image_link;
    }
  }
}
